name: vtp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - matplotlib
  - scipy
  - pytorch
  - torchvision
  - ipykernel
  - tqdm
  # astra
  - python-box
  - torch-geometric
  - segmentation-models-pytorch
  - icecream
  - opencv
  # waymo converter
  - pandas
  - pyarrow
  - pillow
  - pip
  - pip:
      - opencv-python
      - -e .
