name: vtp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - pytorch>=2.3
  - torchvision
  - tqdm
  # waymo converter
  - pandas
  - pyarrow
  - pillow
  - pip
  - pip:
      - ultralytics
      - black
      - -e .
