data:
  train_path: /path/to/train/data
  val_path: /path/to/validation/data  
  test_path: /path/to/test/data

feature_extractor:
  features: [feature1, feature2, feature3]
  train_feature_path: data/features/train.csv #path to store extracted features
  val_feature_path: data/features/val.csv #path to store extracted features
  test_feature_path: data/features/test.csv #path to store extracted features
  regenerate_features: false # whether to regenerate features or use existing ones

training:
  batch_size: 64
  num_epochs: 100
  learning_rate: 0.001

model:
  type: Linear
  num_trajectory_possibilities: 3
