feature_extractor:
  dataset_root: /work/cs-503/santanto/waymo
  feature_root: /work/cs-503/gromb/waymo
  tables:
    images: images.parquet
    ego_poses: ego_poses.parquet
    trajectories: trajectories.parquet
    image_trajectories: image_trajectories.parquet
    latent_features: fe_local_latent_features.parquet


  features:
    image_trajectories:
      - bbox_center_x
      - bbox_center_y
      - bbox_width
      - bbox_height

  #Not using this for now
  train_feature_path: data/features/train.csv #path to store extracted features
  val_feature_path: data/features/val.csv #path to store extracted features
  test_feature_path: data/features/test.csv #path to store extracted features
  regenerate_features: false # whether to regenerate features or use existing ones

training:
  batch_size: 4
  num_epochs: 4
  learning_rate: 0.001
  from_checkpoint: false
  save_to: checkpoint/gnn.pth
  wandb_project: "Hello"
  training_log:
    metric: batch
    steps: 1
  validation_log:
    metric: batch
    steps: 50

model:
  type: GNN
  num_trajectory_possibilities: 3

num_workers: 3