feature_extractor:
  images_path_path: /work/cs-503/santanto/waymo/training__10017090168044687777_6380_000_6400_000/images.parquet
  ego_poses_path: /work/cs-503/santanto/waymo/training__10017090168044687777_6380_000_6400_000/ego_poses.parquet
  trajectories_path: /work/cs-503/santanto/waymo/training__10017090168044687777_6380_000_6400_000/trajectories.parquet
  image_trajectories_path: /work/cs-503/santanto/waymo/training__10017090168044687777_6380_000_6400_000/image_trajectories.parquet
  prediction_targets_path: /work/cs-503/santanto/waymo/training__10017090168044687777_6380_000_6400_000/prediction_targets.parquet
  manifest_path: /work/cs-503/santanto/waymo/training__10017090168044687777_6380_000_6400_000/manifest.json
  window: 4
  future_frames: 5
  num_objects: 4
  polynomial_degree: 3
  trajectory_dims: 3
  target_features:
    x: bbox_center_x
    y: bbox_center_y
    width: bbox_width
    height: bbox_height

  features:
    image_trajectories:
      - bbox_center_x
      - bbox_center_y
      - bbox_width
      - bbox_height

  #Not using this for now
  train_feature_path: data/features/train.csv #path to store extracted features
  val_feature_path: data/features/val.csv #path to store extracted features
  test_feature_path: data/features/test.csv #path to store extracted features
  regenerate_features: false # whether to regenerate features or use existing ones

training:
  batch_size: 64
  num_epochs: 100
  learning_rate: 0.01
  lr_scheduler:
    enabled: true
    warmup_epochs: 10
  from_checkpoint: false
  save_to: checkpoint/lstm_model_paths.pth
  wandb_project: "LSTMModel"

model:
  type: lstm
  num_trajectory_possibilities: 8
  hidden_dim: 64
  polynomial_degree: 3
  spatial_dims:
    - 0
    - 1
  min_refinement_steps: 1
  max_refinement_steps: 10
